# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.   
  config.vm.box = "generic/alpine317"
  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
  end
  
  

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.boot_timeout = 300
  config.vm.define "ael-mousS" do |server|
    server.vm.hostname = "ael-mousS"
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
    server.vm.synced_folder ".", "/vagrant"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", privileged: true, path: "./server_script.sh", args: ["192.168.56.110"]
  end

  config.vm.define "ael-mousSW" do |serverW|
    serverW.vm.hostname = "ael-mousSW"
    serverW.vm.synced_folder ".", "/vagrant"
    serverW.vm.network "private_network", ip: "192.168.56.111"
    serverW.vm.provision "shell", privileged: true, path: "./worker_script.sh", args: [ "192.168.56.110", "192.168.56.111"]
  end

end
