#vagrant file
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.forward_x11 = true

  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192 #8gb
    vb.cpus = 8
  end

  config.vm.define "zihihi" do |node|
    node.vm.hostname = "zihihi"
    node.vm.network "private_network", ip: "192.168.56.110"
    node.vm.synced_folder ".", "/vagrant"

    node.vm.provision "shell", path: "scripts/gitlab.sh"
    node.vm.provision "shell", path: "scripts/argocd.sh"

  end
end 